name: VHDL CI

on:
  push:
    branches:
      - main
    paths:
      - 'GHDL/**'
  pull_request:
    branches:
      - main
    paths:
      - 'GHDL/**'
  workflow_dispatch:

jobs:
  ghdl-test:
    name: Run GHDL tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GHDL
      uses: ghdl/setup-ghdl@v1
      with:
        backend: llvm

    - name: Run testbenches with GHDL
      run: |
        cd GHDL/sim
        chmod +x run.sh
        ./run.sh

    - name: Upload simulation results (logs + waveforms)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simulation-results
        path: |
          GHDL/build/logs
          GHDL/build/waves/*.ghw
          GHDL/build/waves/*.png