name: VHDL CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ghdl-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GHDL
      run: |
        sudo apt update
        sudo apt install -y ghdl gtkwave xvfb

    - name: Run testbenches with GHDL
      run: |
        cd GHDL/sim
        chmod +x run.sh
        ./run.sh --render

    - name: Upload simulation results (logs + waveforms)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simulation-results
        path: |
          GHDL/build/logs
          GHDL/build/waves/*.ghw
          GHDL/build/waves/*.png